---
# roles/puma/tasks/main.yml

- name: Create necessary directories for Puma
  ansible.builtin.file:
    path: "{{ app_path }}/{{ item }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0775'
  loop:
    - tmp/pids
    - tmp/sockets
    - log

- name: Create Puma configuration file
  ansible.builtin.template:
    src: puma.rb.j2
    dest: "{{ app_path }}/config/puma.rb"
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Configure Puma systemd service
  ansible.builtin.template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Start Puma
  ansible.builtin.systemd:
    name: puma
    state: started
    enabled: yes
  become: true
