---
# roles/yarn/tasks/main.yml

- name: Add Yarn repository
  ansible.builtin.get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    mode: '0644'
  become: true

- name: Install Yarn
  ansible.builtin.yum:
    name: yarn
    state: present
  become: true
