---
# roles/yarn/tasks/main.yml

- name: Add Yarn repository
  ansible.builtin.shell: curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo

- name: Install Yarn
  ansible.builtin.shell: "sudo yum install -y yarn"
