# vars/main.yml
rbenv_root: /home/ec2-user/.rbenv
rbenv_path: /home/ec2-user/.rbenv/bin:{{ ansible_env.PATH }}
ruby_version: 3.2.3
bundler_version: 2.3.14
app_path: /home/ec2-user/raisetech-live8-sample-app
db_name: raisetech-lec13
db_user: "{{ lookup('env', 'DB_USER') }}"
db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
db_host: "{{ lookup('env', 'DB_HOST') }}"
alb_dns: "{{ lookup('env', 'ALB_HOST') }}"
s3_bucket: "{{ lookup('env', 'S3_BUCKET') }}"
rds_az: "{{ lookup('env', 'RDSAZ')}}"

