---
# roles/nodejs/tasks/main.yml

- name: Add NodeSource repository
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_16.x | bash -

- name: Install Node.js
  ansible.builtin.yum:
    name: nodejs
    state: present
  become: true
